# Generated by Django 5.0.4 on 2024-04-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.DeleteModel(
            name='Empolyee',
        ),
    ]
