# Generated by Django 5.0.4 on 2024-04-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_app', '0002_employee_delete_empolyee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Empolyee',
        ),
        migrations.AlterModelOptions(
            name='empolyee',
            options={'verbose_name': 'Empolyee', 'verbose_name_plural': 'Empolyees'},
        ),
    ]
